{% set name = "shellcheck" %}
{% set version = "0.6.0" %}
{% set sha256 = "4e6c46751f031095f33f46ad4a4cf51c79fd2398031260132d6b57390a59d293" %}

{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  missing_dso_whitelist:
    - /lib64/libm.so.6           # [linux]
    - /lib64/libutil.so.1        # [linux]
    - /lib64/libpthread.so.0     # [linux]
    - /lib64/libc.so.6           # [linux]
    - /lib64/libdl.so.2          # [linux]
    - /lib64/librt.so.1          # [linux]
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack
    - binutils              # [linux]
    - {{native}}binutils    # [win]

  host:
    - gmp  # [unix]

  run:
    - gmp  # [unix]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
