{% set name = "shellcheck" %}
{% set version = "0.7.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/koalaman/{{ name }}/archive/v{{ version }}.tar.gz             # [not linux]
    sha256: 946cf3421ffd418f0edc380d1184e4cb08c2ec7f098c79b1c8a2c482fe91d877              # [not linux]
  - url: https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz  # [linux]
    sha256: 092f8ece0bb8413c835f4ecc14c9f1157ebb44a36a216e3d617d1048ecdfce1b              # [linux]

build:
  number: 0

  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

requirements:
  build:
    - stack                     # [not linux]
    - {{native}}binutils

  host:
    - gmp  # [osx]

  run:
    - gmp  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPLv3
  license_family: GPL
  license_file: LICENSE      # [not linux]
  license_file: LICENSE.txt  # [linux]
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
