{% set name = "shellcheck" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # use the prebuild binaries provided by the project
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.darwin.x86_64.tar.xz  # [osx]
    sha256: 969bd7ef668e8167cfbba569fb9f4a0b2fc1c4021f87032b6a0b0e525fb77369  # [osx]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.x86_64.tar.xz  # [linux]
    sha256: 969bd7ef668e8167cfbba569fb9f4a0b2fc1c4021f87032b6a0b0e525fb77369  # [linux]

build:
  number: 0
  skip: True  # [not linux64 and not osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
