{% set name = "shellcheck" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # use the prebuild binaries provided by the project
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.darwin.x86_64.tar.xz  # [osx]
    sha256: b080c3b659f7286e27004aa33759664d91e15ef2498ac709a452445d47e3ac23  # [osx]
  - url: https://github.com/koalaman/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.linux.x86_64.tar.xz  # [linux]
    sha256: 64f17152d96d7ec261ad3086ed42d18232fcb65148b44571b564d688269d36c8  # [linux]

build:
  number: 0
  skip: True  # [not linux64 and not osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]

test:
  commands:
    - shellcheck --version
    - shellcheck || true

about:
  home: https://github.com/koalaman/shellcheck
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: ShellCheck, a static analysis tool for shell scripts

extra:
  recipe-maintainers:
    - dbast
