travis:
  secure:
    BINSTAR_TOKEN: SWT8NnawGiyHMg2exuyYWj7A9UNWWEfukE4y1wy2I1GsmphbII02OM1AFjG8AsSETzYQDyVr2yTXguLaudlcyfoQsy/qzyXTiFIN9/447WAkZtaYh0OkANpQxQAJnmgrP+LaGOAPRRJXGF5pAV9G6rxJm+hxj6EVCH6oFa+ws1Un/uiz3w3ohvS0GyjtcsgyRjHKgK7FGnyf6U7fvmRfB69Lg4cFzpOy4igDk9KqXMBK112cJ1eVizdrv9yr9ehkC2VWrBz7NTZR2KjaEFbdlnPGKBuDOghLc/oZSOcwwGKr/1gzGNzwpxVRJR66ETcHwk8gic3HOIdk+yVa+WfdHrf4HFL8lBaO63QvIW9nfXUaZWWjrYA0L91LQvNhE46xB76AvNnx4dv/uJq5kky0b7dwC8Gj/meRsKAZNV+ui5IVowTVftERu+y94LDTfdfEJ/SpTqqvw86tKIWfcDcuWNosmt1ad5E1NDmx18oIcP1hfFjcAxDLVGg/IM5SMIgGiPygkVJGCg6IiWrWcDDNSwenl6v2tReaqk57x5x4EpJNIDmU8Jhe0VyshJIByxDaHqS7nDIfDuxQkwK1+x++j6bIldwCKsKH/Zxla7zHzT/1lQqh0Tt0xVGZH8cj9Fh9Q8Fw9804bEKVHbM/flKojk9b3RAJIxonifEIHDlqisg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
